### ISSUE TITLE
Consider Transition object being a promise sublcass

### ISSUE THREAD

**Issue by stefanpenner** [tildeio/router.js#95]
The Transition object already mimics a thenable via `then` but lacks `catch` and `finally` etc, why not just make it a subclass

https://github.com/tildeio/router.js/blob/master/lib/router/transition.js

**Comment by jmeas** [comment]
Resolved in https://github.com/tildeio/router.js/commit/83f33bad29472ec03a973117e23c52b241fa1440

**Comment by stefanpenner** [comment]
@jmeas no, that doesn't resolve it. That merely creates a promise like entity, it does not create a subclass.

**Comment by jmeas** [comment]
Ah, gotcha :+1:

**Comment by sandstrom** [comment]
I'm doing some issues-gardening 🍀 🌷  and stumbled upon this. Is this still an issue? if not, perhaps it can be closed?

**Comment by rwjblue** [comment]
Yes, it is still an issue.
